leftnav:
- identifier: dc586c6b-7538-e839-02aa-2cd25b61af0e
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 0f80c5b5-a565-9d1f-54a4-614ad2c0664f
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 3ab369cc-0995-69f4-4c1d-2bacb52886ae
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: ad119e6d-6cb5-8c67-4d0e-8dea760f080b
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: d2361ffc-e373-03b0-ee75-b5860fb60705
  name: Exams
  pageRef: /pages/exams
  weight: 50
- identifier: 8e351913-73d7-7977-e2c0-b5691c17ddc5
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 60
